services:

  postgres:
    image: postgres
    container_name: vsv-shop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5zm7aa8o
      PGDATA: /data/postgres
      POSTGRES_DB: vsv
    volumes:
      - postgres:/data/postgres
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - default


  redis:
    image: redis:latest
    container_name: vsv-shop-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=5zm7aa8o
      - REDIS_PORT=6379
    networks:
      - default
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#    container_name: vsv-shop-es
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports:
#      - "9200:9200"
#    networks:
#      - default
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.11.1
#    container_name: vsv-shop-kibana
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    networks:
#      - default
#    depends_on:
#      - elasticsearch

networks:
  default:
    name: vsv-shop

volumes:
  postgres:
#  esdata:

# docker compose up -d --build